# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy-test-page:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Run Tests
      run: go test -coverprofile=coverage.out ./... 
    - name: Go Check Coverage
      run: go tool cover -func=coverage.out 
    - name: Make Website Folder
      run: mkdir src
    - name: Copy Go Files To Website
      run: cp main.go src/
    - name: List Files In Website Folder
      run: ls src/
    - name: Create HTML Cov File
      run: go tool cover -html coverage.out -o src/index.html
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
       path: 'src/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
    - name: upload-files
      uses: actions/upload-artifact@v3
      with:
       name: recipes
       path: src/
    - name: Upload recipes to release
      uses: svenstaro/upload-release-action@v2
      with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: src/index.html
       tag: ${{ github.ref }}
       overwrite: true 
       file_glob: true
