name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
      
permissions:
  actions: read|write
  checks: read|write
  contents: read|write
  deployments: read|write
  id-token: read|write
  issues: read|write
  discussions: read|write
  packages: read|write
  pages: read|write
  pull-requests: read|write
  repository-projects: read|write
  security-events: read|write
  statuses: read|write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    env:
          GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/users/gowhale/projects/1/
          github-token: ${{ secrets.GITHUB_TOKEN }}
